# Generated by Django 5.2.3 on 2025-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
